### ISSUE TITLE
Create network requests to mock server

### ISSUE THREAD

**Issue by tednaphil** [Brain-Defrost/Brain-Defrost_FE#25]
See Mock Server documentation [here](https://turing-school-of-software-and-design-student-plan-team-2.postman.co/workspace/Brain-Defrost~10af0c71-fc74-4690-9d20-4a3cc1748c54/documentation/33651209-01ffb49c-138a-4861-b654-f368c6e83d3f)

**Comment by tednaphil** [comment]
@Chavezgm @kohljd @laurarvegav I made an update to the `Final Game Stats` mock server response to remedy a syntax issue in the JSON (just a couple of commas!)

@EthanDuvall The `useEffect` invocation in the `App.tsx` component is only there to run the network requests and console log the data - feel free to discard once you start making requests where/when they're actually needed.

**Comment by EthanDuvall** [comment]
Sounds good thank you!
