### ISSUE TITLE
Define Routes/Paths

### ISSUE THREAD

**Issue by tednaphil** [Brain-Defrost/Brain-Defrost_FE#29]
- [x] `/`
- [x] `/game/lobby/:gameid`
- [x] `/join/:gameid`
- [x] `/game/play/:gameid`
- [x] `/game/results/:gameid`
- [x] `/*`

**Comment by tednaphil** [comment]
@EthanDuvall I added the `/Brain-Defrost_FE` path as the `basename` in the `BrowserRouter` component so the path will still be `/` for the home page.

I also added an h2 to each component rendered for each path so we could easily see which path led where successfully while we've developing. Feel free to discard at any point

**Comment by EthanDuvall** [comment]
Oh nice That cleans things up
