### ISSUE TITLE
As a user, when I click the "Create Game" button, I'm taken to the game lobby

### ISSUE THREAD

**Issue by tednaphil** [Brain-Defrost/Brain-Defrost_FE#5]
I see:
- [x] Shareable link for others to join the game (look into auto-copy feature)
- [x] My display name
- [x] Display names of other players who have joined
- [x] `Start Game` button
- [x] URL is `lobby/:gameid`

Sad path:

- [ ] If game creation is unsuccessful, I will see a `Try Again` message/modal and a cleared form

**Comment by tednaphil** [comment]
I'm going to work on creating the `Lobby` elements today and will also update the `formData` object to implement a POST request with the data to create a game. I'll do this work on the `feature/future-player-stories` branch.

**Comment by EthanDuvall** [comment]
Sounds good i can get started on looking into the web sockets so that we cna use them when ready

**Comment by tednaphil** [comment]
Hi all! Work for the sad paths for this issue and issue #7 will be completed once we're making network requests to the true backend app.
